version: '3'
services:
  frontend:
    container_name: front
    build:
      context: front
    ports:
      - 3000:3000
    volumes:
      - ./front/project:/project:cached
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    container_name: back
    build:
      context: backend
    volumes:
      - ./backend/src:/go/src/github.com/MikiWaraMiki/nuxt-go-ddd-sample/backend/src
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: "dev.db"
      MYSQL_HOST: 'db'
      MYSQL_PORT: 3306
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: db
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql/volumes:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
  proxy:
    build:
      context: nginx
    container_name: app-nginx
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
    ports:
      - 8000:8000
    depends_on:
      - backend
      - frontend
