version: '3'
services:
  front:
    container_name: front
    build:
      context: front
    ports:
      - 8000:8000
    volumes:
      - ./front/src:/src:cached
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
