development:
    dialect: mysql
    dir: migrate/sql
    datasource: root:password@tcp(db:3306)/dev.db?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true
test:
    dialect: mysql
    dir: migrate/sql
    datasource: root:password@tcp(db:3306)/test.db?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true
